# --log-level
# CRITICAL = 0
# ERROR = 1
# WARNING = 2
# NOTICE = 3
# INFO = 4
# DEBUG = 5
LogLevel="WARNING"

[Init]
# --ocfl-version
OCFLVersion="1.1" # supported versions 1.0 1.1
# --digest
DigestAlgorithm="sha512"

[Add]
# --user-name
UserName="unknown user"
# --user-address
UserAddress="mailto:someone@internet"
# --fixity
Fixity="md5,sha256,blake2b-384"
# --digest
DigestAlgorithm="sha512"
# --message
Message="initial commit"

[Update]
# --user-name
UserName="unknown user"
# --user-address
UserAddress="mailto:somewone@internet"
# --echo
Echo=false # do not reflect deletion in source folder
# --digest
DigestAlgorithm="sha512"
# --message
Message="update message"

[Create]
# --ocfl-version
OCFLVersion="1.1" # supported versions 1.0 1.1
# --digest
DigestAlgorithm="sha512"

# --user-name
UserName="unknown user"
# --user-address
UserAddress="mailto:someone@internet"
# --fixity
#Fixity="md5,sha256"
Fixity="md5,sha256,blake2b-384"
# --message
Message="Initial commit"

[Stat]
# --stat-info
#Info = "ExtensionConfigs,objects,objectversions,objectextensionconfigs"
Info = "objects,objectversions"

[Extract]
# --extract-manifest
Manifest = true

[ExtractMeta]
# --format
Format = "json"
# --output
Output = ""

[Indexer]
# --with-indexer
Enable=true

# mapping of pronom id to mimetype if not found in siegfried
[Indexer.Siegfried.MimeMap]
"x-fmt/92" = "image/psd"
"fmt/134" = "audio/mp3"
"x-fmt/184" = "image/x-sun-raster"
"fmt/202" = "image/x-nikon-nef"
"fmt/211" = "image/x-photo-cd"
"x-fmt/383" = "image/fits"
"fmt/405" = "image/x-portable-anymap"
"fmt/406" = "image/x-portable-graymap"
"fmt/408" = "image/x-portable-pixmap"
"fmt/436" = "image/x-adobe-dng"
"fmt/437" = "image/x-adobe-dng"
"fmt/592" = "image/x-canon-cr2"
"fmt/642" = "image/x-raw-fuji"
"fmt/662" = "image/x-raw-panasonic"
"fmt/668" = "image/x-olympus-orf"
"fmt/986" = "text/xmp"
"fmt/1001" = "image/x-exr"
"fmt/1040" = "image/vnd.ms-dds"
"fmt/1781" = "image/x-pentax-pef"

# relevance of mimetype for sorting
# relevance < 100: rate down
# relevance > 100: rate up
# default = 100
[Indexer.MimeRelevance.1]
Regexp = "^application/octet-stream$"
Weight = 1
[Indexer.MimeRelevance.2]
Regexp = "^text/plain$"
Weight = 3
[Indexer.MimeRelevance.3]
Regexp = "^audio/mpeg$"
Weight = 6
[Indexer.MimeRelevance.4]
Regexp = "^video/mpeg$"
Weight = 5
[Indexer.MimeRelevance.5]
Regexp = "^text/.+$"
Weight = 4
[Indexer.MimeRelevance.6]
Regexp = "^application/vnd\\..+"
Weight = 4
[Indexer.MimeRelevance.7]
Regexp = "^application/.+"
Weight = 2
[Indexer.MimeRelevance.8]
Regexp = "^.+/x-.+"
Weight = 80
